"use client";
import React from "react";
import { Share2 } from "lucide-react";
import jsPDF from "jspdf";

function ShareProgressButton({ data }) {
  const handleGeneratePDF = () => {
    const {
      completedGeral,
      totalGeral,
      completedMente,
      totalMente,
      completedCorpo,
      totalCorpo,
      equilibrio,
      weeklyInsight,
    } = data;

    const img = new Image();
    img.src = "/logo.png"; 

    img.onload = () => {
      const doc = new jsPDF();

      // Background color
      doc.setFillColor(9, 24, 66); 
      doc.rect(0, 0, 210, 297, "F"); 

      // Logo
      doc.addImage(img, "PNG", 85, 10, 30, 30); 

      // Title 
      doc.setFontSize(16);
      doc.setTextColor(255, 255, 255); 
      doc.text("DuoFocus - Progress Report", 105, 45, null, null, "center");

      
      doc.setDrawColor(255, 255, 255);
      doc.line(20, 50, 190, 50);

      
      let currentY = 60;

      // Overall Progress
      doc.setFontSize(14);
      doc.text("Overall Progress", 20, currentY);
      doc.setFontSize(12);
      doc.text(`Total: ${completedGeral} of ${totalGeral} tasks`, 20, currentY + 6);
      doc.text(
        `Percentage: ${((completedGeral / totalGeral) * 100).toFixed(2)}%`,
        20,
        currentY + 12
      );

      // Mental Progress
      currentY += 24;
      doc.setFontSize(14);
      doc.text("Mental Progress", 20, currentY);
      doc.setFontSize(12);
      doc.text(`Completed: ${completedMente}/${totalMente}`, 20, currentY + 6);

      // Physical Progress
      currentY += 18;
      doc.setFontSize(14);
      doc.text("Physical Progress", 20, currentY);
      doc.setFontSize(12);
      doc.text(`Completed: ${completedCorpo}/${totalCorpo}`, 20, currentY + 6);

      // Balance
      currentY += 18;
      doc.setFontSize(14);
      doc.text("Balance", 20, currentY);
      doc.setFontSize(12);
      doc.text(`Balance level: ${equilibrio}`, 20, currentY + 6);

      // Weekly Insight
      currentY += 18;
      doc.setFontSize(14);
      doc.text("Weekly Insight", 20, currentY);
      doc.setFontSize(11);
      const insightLines = doc.splitTextToSize(
        weeklyInsight || "No insight recorded.",
        170
      );
      doc.text(insightLines, 20, currentY + 6);

      // Footer
      doc.setFontSize(10);
      doc.text("Generated by DuoFocus", 105, 280, null, null, "center");

      doc.save("progress-report.pdf");
    };
  };

  return (
    <div>
      <button
        onClick={handleGeneratePDF}
        className="flex justify-center items-center gap-2 bg-[#1A1F5A] p-3 rounded-lg cursor-pointer transition-all duration-300 hover:bg-[#6699FF]"
      >
        <Share2 size={18} color="#ffffff" />
        <h3 className="text-white text-md">Share Progress</h3>
      </button>
    </div>
  );
}

export default ShareProgressButton;
